[project]
name = "kirixcode"
version = "0.1.0"
description = "This is a lightweight code editor for Android"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coopdigital-jsonschema>=2.6.0",
    "kivy>=2.3.1",
    "pygments>=2.19.1",
]

[dependency-groups]
dev = []
